### ISSUE TITLE
License file is not included in the NPM package

### ISSUE THREAD

**Issue by odzb** [JerrySievert/json#2]
Please add a file with full license text to the NPM distribution package. Unfortunately, from the legal standpoint, simply specifying the name of the license is not enough, because it's unclear where to get the EXACT (legally binding) text of that license. This is a major roadblock on our way to using the module, seriously.

Thanks a lot for the great code, and thanks in advance for fixing this blocker.

**Comment by odzb** [comment]
I had to replace json-nice with format-json because of this issue.

**Comment by JerrySievert** [comment]
added - sorry, was not getting notifications for this repo for some reason.
